-- 1. Create the announcements table
CREATE TABLE IF NOT EXISTS public.announcements (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    content TEXT NOT NULL,
    type TEXT DEFAULT 'info' CHECK (type IN ('info', 'warning', 'urgent')),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    created_by UUID REFERENCES auth.users(id) ON DELETE SET NULL
);

-- 2. Enable Row Level Security (RLS)
ALTER TABLE public.announcements ENABLE ROW LEVEL SECURITY;

-- 3. Create Policy: Everyone can view announcements (for the Bell Icon)
CREATE POLICY "Anyone can view announcements" 
ON public.announcements FOR SELECT 
USING (true);

-- 4. Create Policy: Only admins can insert, update or delete announcements
CREATE POLICY "Only admins can manage announcements" 
ON public.announcements FOR ALL 
USING (
  (SELECT role FROM public.users WHERE id = auth.uid()) = 'admin'
);

-- 5. Per-user read status table
CREATE TABLE IF NOT EXISTS public.user_announcement_status (
    user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    announcement_id BIGINT NOT NULL REFERENCES public.announcements(id) ON DELETE CASCADE,
    is_read BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    PRIMARY KEY (user_id, announcement_id)
);

CREATE INDEX IF NOT EXISTS idx_user_announcement_status_user_id
ON public.user_announcement_status (user_id);

CREATE INDEX IF NOT EXISTS idx_user_announcement_status_announcement_id
ON public.user_announcement_status (announcement_id);

-- 6. Enable RLS and lock each row to its owner
ALTER TABLE public.user_announcement_status ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view their own announcement status"
ON public.user_announcement_status FOR SELECT
USING (auth.uid() = user_id);

CREATE POLICY "Users can insert their own announcement status"
ON public.user_announcement_status FOR INSERT
WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can update their own announcement status"
ON public.user_announcement_status FOR UPDATE
USING (auth.uid() = user_id)
WITH CHECK (auth.uid() = user_id);