-- 1. Create the announcements table
CREATE TABLE IF NOT EXISTS public.announcements (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    content TEXT NOT NULL,
    type TEXT DEFAULT 'info' CHECK (type IN ('info', 'warning', 'urgent')),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    created_by UUID REFERENCES auth.users(id) ON DELETE SET NULL
);

-- 2. Enable Row Level Security (RLS)
ALTER TABLE public.announcements ENABLE ROW LEVEL SECURITY;

-- 3. Create Policy: Everyone can view announcements (for the Bell Icon)
CREATE POLICY "Anyone can view announcements" 
ON public.announcements FOR SELECT 
USING (true);

-- 4. Create Policy: Only admins can insert, update or delete announcements
CREATE POLICY "Only admins can manage announcements" 
ON public.announcements FOR ALL 
USING (
  (SELECT role FROM public.users WHERE id = auth.uid()) = 'admin'
);